### ISSUE TITLE
undefined method `zero?' for "/timeout":String (NoMethodError)

### ISSUE THREAD

**Issue by sumeshbabukonni** [pelargir/auto-session-timeout#1]
Hi,

When I use jquery-auto-session-timeout-0.5.1 with Jruby 1.5.1,

 I got the following error during the building of my Jruby application

D:/My Projects/ruby/ama_etoms_v1/config/routes.rb:100: undefined method `zero?' for "/timeout":String (NoMethodError)
        from C:/NetBeans 6.9.1/ruby/jruby-1.5.1/lib/ruby/gems/1.8/gems/actionpack-2.3.9/lib/action_controller/routing/route_set.rb:227:in`draw'
        from D:/My Projects/ruby/ama_etoms_v1/config/routes.rb:1
        from D:/My Projects/ruby/ama_etoms_v1/config/routes.rb:171:in `load'
        from C:/NetBeans 6.9.1/ruby/jruby-1.5.1/lib/ruby/gems/1.8/gems/activesupport-2.3.9/lib/active_support/dependencies.rb:171:in`load_with_new_constant_marking'
        from C:/NetBeans 6.9.1/ruby/jruby-1.5.1/lib/ruby/gems/1.8/gems/activesupport-2.3.9/lib/active_support/dependencies.rb:547:in `new_constants_in'
        from C:/NetBeans 6.9.1/ruby/jruby-1.5.1/lib/ruby/gems/1.8/gems/activesupport-2.3.9/lib/active_support/dependencies.rb:171:in`load_with_new_constant_marking'
        from C:/NetBeans 6.9.1/ruby/jruby-1.5.1/lib/ruby/gems/1.8/gems/actionpack-2.3.9/lib/action_controller/routing/route_set.rb:287:in `load_routes!'
        from C:/NetBeans 6.9.1/ruby/jruby-1.5.1/lib/ruby/gems/1.8/gems/actionpack-2.3.9/lib/action_controller/routing/route_set.rb:287:in`each'
         ... 10 levels...
        from C:/NetBeans 6.9.1/ruby/jruby-1.5.1/lib/ruby/gems/1.8/gems/rails-2.3.9/lib/commands/server.rb:84
        from C:/NetBeans 6.9.1/ruby/jruby-1.5.1/lib/ruby/gems/1.8/gems/rails-2.3.9/lib/commands/server.rb:3:in `require'
        from script\server:3

When I commented the line 
 map.timeout '/timeout', :controller => 'sessions', :action => 'timeout'
the build was a success. But the auto session time out doesn't works.

I am using the autosessiontimeout gem, as given in the read me file.

Please have look on this issue..

**Comment by pelargir** [comment]
@sumeshbabukonni did this work for you?

**Comment by pelargir** [comment]
Please reopen if this is still a problem.
