### ISSUE TITLE
update the gem

### ISSUE THREAD

**Issue by dowi** [pelargir/auto-session-timeout#10]
- can you please update the gem to be 0.9.3?

thanks a lot!

**Comment by pelargir** [comment]
I'm not using this gem any longer and don't have time to keep it updated, but I'm happy to accept pull requests if you want to do this yourself.

**Comment by maurercw** [comment]
I think he's likely asking for the new gem version to be released and published to rubygems.org.  But if he's not, that's what I'd like to have happen!

**Comment by pelargir** [comment]
Done!
