### ISSUE TITLE
ActionController::InvalidAuthenticityToken

### ISSUE THREAD

**Issue by bennyzr** [pelargir/auto-session-timeout#19]
When the app does timeout as expected and redirects to the login route I invariably get an ActionController::InvalidAuthenticityToken when trying to login and create a session. Any ideas?

Routes:
	devise_scope :user do
		match 'active'  => 'users/sessions#active',  via: :get
		match 'timeout' => 'users/sessions#timeout', via: :get
		get 'login', to: 'devise/sessions#new'
	end

Log:
Started GET "/login" for 127.0.0.1 at 2017-06-07 10:16:23 -0400
Processing by Devise::SessionsController#new as HTML
  Rendering devise/sessions/new.html.erb within layouts/application
  Rendered devise/shared/_links.html.erb (0.9ms)
  Rendered devise/sessions/new.html.erb within layouts/application (23.3ms)
  Rendered layouts/_messages.html.erb (0.3ms)
  Rendered layouts/_navigation.html.erb (3.9ms)
Completed 200 OK in 267ms (Views: 265.3ms | ActiveRecord: 0.0ms)

Started POST "/users/sign_in" for 127.0.0.1 at 2017-06-07 10:19:50 -0400
Processing by Users::SessionsController#create as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", "user"=>{"email"=>"john@yahoo.com", "password"=>"[FILTERED]"}, "commit"=>"Log in"}
Can't verify CSRF token authenticity.
Completed 422 Unprocessable Entity in 2ms (ActiveRecord: 0.0ms)

**Comment by killernova** [comment]
It was described in this PR: [#15](https://github.com/pelargir/auto-session-timeout/pull/15l).
This is caused after some time, the session in server was deleted, so when the form submits, the csrf-token can not be found in server and raised the error.

**Comment by bennyzr** [comment]
Ok. Any idea when this pull request will get merged into master?

**Comment by killernova** [comment]
No idea, many days has been passed since the pr submitted, and the author of pr was supposed to modify codes for some 'code style reason', but he never shows again.

**Comment by gdemonie** [comment]
Any update on this please?

**Comment by pelargir** [comment]
If someone would like to take the work in #15 and submit it as a new PR, I'd be happy to accept the merge. The code in #15 on line 10 has a very long ternary tacked on the end and that's what I was asking the original submitter to fix. It's messy and hard to understand.

**Comment by pelargir** [comment]
Thank you @davegudge
