### ISSUE TITLE
NoMethodError (undefined method `active_url'  for a Controller...)

### ISSUE THREAD

**Issue by zipho** [pelargir/auto-session-timeout#2]
'active_url' seems to be breaking the Gem in my rails 3.2.11.

What could be the issue?

/home.rvm/gems/ruby-1.9.3-p392/gems/auto-session-timeout-0.9.2/lib/auto_session_timeout.rb:14:in `block in auto_session_timeout'

**Comment by wingalong** [comment]
Hi, I also get 'active_url' problem, /home.rvm/gems/ruby-1.9.3-p392/gems/auto-session-timeout-0.9.2/lib/auto_session_timeout.rb:14:in `block in auto_session_timeout'.

How did you solve it?

**Comment by pelargir** [comment]
Are you using Rails 4? I haven't updated this gem in a long time. The latest version of Rails may not like the routing syntax. Something like this should work:

    ActionController::Routing::Routes.draw do
        get 'active' => 'sessions#active'
        get 'timeout' => 'sessions#timeout'
    end

**Comment by wingalong** [comment]
Yes, I am now using Rails 4.2.3       Ruby 1.9.3.

All my other routes.rb code is like :
ActionController::Routing::Routes.draw do |map|
   map.resources :session
end

So I put 
ActionController::Routing::Routes.draw do
  get 'active' => 'sessions#active'
  get 'timeout' => 'sessions#timeout'
end

at the end of routes.rb file, after <end> tag. server has this error /home/weiming/maspore/config/routes.rb:130:in `block in <top (required)>': undefined method `get' for main:Object (NoMethodError).

Thank you!

**Comment by pelargir** [comment]
Don't use 2 blocks. Your routing file should only have a single block. And if you're truly on Rails 4.2 you shouldn't be passing map to the block anyway:

    ActionController::Routing::Routes.draw do
      resources :session
      get 'active' => 'sessions#active'
      get 'timeout' => 'sessions#timeout'
    end

Are you sure you're on Rails 4.2?

**Comment by wingalong** [comment]
Yes, I am sure it is the Rails 4.2.3. I am maintaining the system so I am not sure how it is working like that. And the even though I replace the whole routes.rb file with 
ActionController::Routing::Routes.draw do
...
end
It does not work.

Is it possible to be something like 
  map.resources :session
  map.connect '/session/active', :controller => 'session', :action => 'active'
  map.connect '/session/timeout', :controller => 'session', :action => 'timeout'

**Comment by wingalong** [comment]
Hi, I am not saying there is any problem with your plugin. Just asking for help on how to solve the problem. "get" is not a authorize method in my routes.rb under |map|. Is there any way to write the route config in |map| way to use the plugin?

Thank you!

**Comment by levelone** [comment]
Hi @pelargir, currently trying this gem out, and had this same issue with @zipho but got it resolved by adding:

```
match 'active'  => 'sessions#active',  via: :get
match 'timeout' => 'sessions#timeout', via: :get
```

My concern now is, after setting my timeout to 5.minutes (testing purposes) nothing would happen. I followed the steps and nothing happens. Nor do 'active' and 'timeout' ever get called.. How do we know if the timer is running?

**Comment by pelargir** [comment]
Glad you got it working. The routes you used are, incidentally, identical to the routes I suggest in the README. :)

If you tail your Rails log file you should see a GET request to the #active controller action being sent every 60 seconds. If you aren't seeing this "heartbeat" then something is wrong. You're probably getting a JavaScript error. Open the developer console in Chrome or Safari to see the error.
