### ISSUE TITLE
Inactivity is not detected

### ISSUE THREAD

**Issue by jpriollaud** [pelargir/auto-session-timeout#30]
I'm getting the active heartbeat every 1 minute.

`  def auto_timeout
    2.minutes
  end`

I never get a timeout.  Where should I look for clues?

I tried both:
`  def timeout
    signout_user # my existing method
  end`
`  def timeout
    render_session_timeout
  end`

Rails 5.0.7

**Comment by pelargir** [comment]
Check your browser's JavaScript console for errors. It sounds like the JS may not be doing the right thing when the timeout occurs.
