### ISSUE TITLE
Rails 7 support

### ISSUE THREAD

**Issue by vseguin** [pelargir/auto-session-timeout#34]
Rails 7 was released a few weeks ago :)

The gemspec currently requires that actionpack be lower than version 7. Could this be bumped up?

**Comment by pelargir** [comment]
I'd be happy to, however, I've not tested this gem against Rails 7 yet. Have you?

**Comment by pelargir** [comment]
This has been done in [v0.9.9](https://github.com/pelargir/auto-session-timeout/releases/tag/v0.9.9)

**Comment by vseguin** [comment]
Thank you @pelargir !
