### ISSUE TITLE
Make compatible with Rails 7.1

### ISSUE THREAD

**Issue by tim-s-ccs** [pelargir/auto-session-timeout#43]
With the recent release of Rails 7.1, this gem now needs updating so that it is compatible.

I've created a [Pull Request #42](https://github.com/pelargir/auto-session-timeout/pull/42) to add Rails v7.1 to the testing matrix (as well as added tests for newer versions of ruby too)

**Comment by pelargir** [comment]
Thanks for the contribution. It's been merged.
