### ISSUE TITLE
Create a new release with the compatibility of Rails 7.1

### ISSUE THREAD

**Issue by tim-s-ccs** [pelargir/auto-session-timeout#44]
Now that checks have been added to make sure the [gem is compatible with Rails 7.1](https://github.com/pelargir/auto-session-timeout/pull/42) it would be good to create a new release so that we can use it in our Rails 7.1 projects.

This is currently blocking me making the upgrade to Rails 7.1 on some of my projects (though I know I could always target the git branch)

**Comment by pelargir** [comment]
Done. See https://rubygems.org/gems/auto-session-timeout

**Comment by tim-s-ccs** [comment]
> Done. See https://rubygems.org/gems/auto-session-timeout

Thank you @pelargir!
