### ISSUE TITLE
protect_from_forgery exceptions in auto_session_timeout method raises error with `raise_on_missing_callback_actions = true` 

### ISSUE THREAD

**Issue by gfmurphy** [pelargir/auto-session-timeout#46]
**Steps to reproduce**
1. Create rails 7.1.x app
2. Ensure `config.raise_on_missing_callback_actions = true` set
3. Add `auto_session_timeout` to controller
4. Load a page

**Expected results**
Page loads

**Actual results**
Unknown action returned (404 status)

**Notes**

* [protect_from_forgery](https://github.com/pelargir/auto-session-timeout/blob/6c6849a55c0a5a38d70527f2f54af84dc508ad17/lib/auto_session_timeout.rb#L9) with except clause is root cause

**Question**
Since `active` and `timeout` are documented to require `get` method, can we remove the `protect_from_forgery` call altogether? Is it required for `get`? This would allow us to run application with `raise_on_missing_callback_actions = true`

**Comment by pelargir** [comment]
That's correct, `protect_from_forgery` is not required for GET requests. I'd be happy to merge a PR if you create one.

**Comment by pelargir** [comment]
Resolved by https://github.com/pelargir/auto-session-timeout/pull/47
