### ISSUE TITLE
auto_session_timeout_js is not defined

### ISSUE THREAD

**Issue by lgrains** [pelargir/auto-session-timeout#9]
I get the error `auto_session_timeout_js is not defined` after I added this into my layout:

```
<% if (current_account) %>
   <%= auto_session_timeout_js %>
<% end %>
```

I'm using Rails 4.2.0
I think I have everything else set up correctly - do you have any suggestions?

One more edit, I installed `jquery-auto-session-timeout` but putting it in my Gemfile and running bundle install. However, I still get the same error.

Thanks!

**Comment by pelargir** [comment]
Seems like the helper providing the #auto_session_timeout_js method isn't getting loaded properly. This gem has only been tested against Rails 3. I have no idea if it works with Rails 4 or not.

**Comment by davegudge** [comment]
I don't think this is an issue anymore. I followed the readme and successfully installed using a Rails5 setup.

**Comment by webaholik** [comment]
Verified working in 4.2.0 as of today!

**Comment by pelargir** [comment]
@lgrains please re-open this issue if you're still getting the undefined method error.
